## Imports

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install unidecode
from unidecode import unidecode


import os
import pandas as pd
from vega_datasets import data\

pd.set_option('display.max_columns', 35)

Collecting unidecode
  Downloading Unidecode-1.3.8-py3-none-any.whl.metadata (13 kB)
Downloading Unidecode-1.3.8-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.5/235.5 kB 3.8 MB/s eta 0:00:00
Installing collected packages: unidecode
Successfully installed unidecode-1.3.8

In [ ]:
notebook_path = os.path.abspath("Atividade 03 - Pandas.ipynb")
notebook_dir = os.path.dirname(notebook_path)
relative_path = os.path.relpath('/content/drive/MyDrive/soulcode/dataset/Base de dados - Dados sobre desgaste de funcionarios.csv', notebook_dir)
absolute_path = os.path.join(notebook_dir, relative_path)

## Limpeza dos dados

- Nomes de colunas inconsistentes como maisuculo, minusculo ou espaços entre as palavras
- Dados faltantes
- Diferentes idiomas #TODO:Entender essa parte


Nos iremos usar metodos Head,tail,columns,shape e info para realizar o diagnosticos dos dados

In [ ]:
df = pd.read_csv(absolute_path, sep=',')
df.head()

,Idade,Demissão,Viagem de negócios,Diárias recebidas,Departamento,Distância de Casa,Escolaridade,Área de Formação,Número de contratos de trabalho na empresa,ID Funcionário,Nível de Satisfação com o ambiente de trabalho,Gênero,Salário por hora,Nível de envolvimento com o trabalho,Nível hierárquico,Cargo,Satisfação com o trabalho,Estado civil,Renda mensal,Salário Mensal,qtde de empresas que já trabalhou,Maior de idade,Faz hora extra,percentual de aumento de salário,score de performance,Satisfação nas relações Não trabalho,Jornada padrão de trabalho,opção de remaunração variável em ações,Total de anos trabalhados,Qtde de treinamentos realizados no último ano,Equilíbrio vida trabalho,Total de anos trabalhados na empresa,Anos trabalhados na função atual,Anos desde a última promoção,Anos trabalhando com o atual gestor
0,41,Sim,Viaja raramente,1102,Vendas,1,2,Ciências Humanas,1,1,2,Feminino,94,3,2,Executivo de vendas,4,Solteiro,5993,19479,8,Sim,Sim,11,3,1,80,0,8,0,1,6,4,0,5
1,49,Não,Viaja frequentemente,279,Pesquisa e Desenvolvimento,8,1,Ciências Humanas,1,2,3,Masculino,61,2,2,Pesquisador cientista,2,Casado,5130,24907,1,Sim,Não,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Sim,Viaja raramente,1373,Pesquisa e Desenvolvimento,2,2,Outras,1,4,4,Masculino,92,2,1,Técnico de Laboratório,3,Solteiro,2090,2396,6,Sim,Sim,15,3,2,80,0,7,3,3,0,0,0,0
3,33,Não,Viaja frequentemente,1392,Pesquisa e Desenvolvimento,3,4,Ciências Humanas,1,5,4,Feminino,56,3,1,Pesquisador cientista,3,Casado,2909,23159,1,Sim,Sim,11,3,3,80,0,8,3,3,8,7,3,0
4,27,Não,Viaja raramente,591,Pesquisa e Desenvolvimento,2,1,Ciências Médicas,1,7,1,Masculino,40,3,1,Técnico de Laboratório,2,Casado,3468,16632,9,Sim,Não,12,3,4,80,1,6,3,3,2,2,2,2

In [ ]:
df.tail()

,Idade,Demissão,Viagem de negócios,Diárias recebidas,Departamento,Distância de Casa,Escolaridade,Área de Formação,Número de contratos de trabalho na empresa,ID Funcionário,Nível de Satisfação com o ambiente de trabalho,Gênero,Salário por hora,Nível de envolvimento com o trabalho,Nível hierárquico,Cargo,Satisfação com o trabalho,Estado civil,Renda mensal,Salário Mensal,qtde de empresas que já trabalhou,Maior de idade,Faz hora extra,percentual de aumento de salário,score de performance,Satisfação nas relações Não trabalho,Jornada padrão de trabalho,opção de remaunração variável em ações,Total de anos trabalhados,Qtde de treinamentos realizados no último ano,Equilíbrio vida trabalho,Total de anos trabalhados na empresa,Anos trabalhados na função atual,Anos desde a última promoção,Anos trabalhando com o atual gestor
1465,36,Não,Viaja frequentemente,884,Pesquisa e Desenvolvimento,23,2,Ciências Médicas,1,2061,3,Masculino,41,4,2,Técnico de Laboratório,4,Casado,2571,12290,4,Sim,Não,17,3,3,80,1,17,3,3,5,2,0,3
1466,39,Não,Viaja raramente,613,Pesquisa e Desenvolvimento,6,1,Ciências Médicas,1,2062,4,Masculino,42,2,3,Reprentante de saúde,1,Casado,9991,21457,4,Sim,Não,15,3,1,80,1,9,5,3,7,7,1,7
1467,27,Não,Viaja raramente,155,Pesquisa e Desenvolvimento,4,3,Ciências Humanas,1,2064,2,Masculino,87,4,2,Diretor de manufatura,2,Casado,6142,5174,1,Sim,Sim,20,4,2,80,1,6,0,3,6,2,0,3
1468,49,Não,Viaja frequentemente,1023,Vendas,2,3,Ciências Médicas,1,2065,4,Masculino,63,2,2,Executivo de vendas,2,Casado,5390,13243,2,Sim,Não,14,3,4,80,0,17,3,2,9,6,0,8
1469,34,Não,Viaja raramente,628,Pesquisa e Desenvolvimento,8,3,Ciências Médicas,1,2068,2,Masculino,82,4,2,Técnico de Laboratório,3,Casado,4404,10228,2,Sim,Não,12,3,1,80,0,6,3,4,4,3,1,2

In [ ]:
df.columns

Index(['Idade', 'Demissão', 'Viagem de negócios', 'Diárias recebidas',
       'Departamento', 'Distância de Casa', 'Escolaridade', 'Área de Formação',
       'Número de contratos de trabalho na empresa', 'ID Funcionário',
       'Nível de Satisfação com o ambiente de trabalho', 'Gênero',
       'Salário por hora', 'Nível de envolvimento com o trabalho',
       'Nível hierárquico', 'Cargo', 'Satisfação com o trabalho',
       'Estado civil', 'Renda mensal', 'Salário Mensal',
       'qtde de empresas que já trabalhou', 'Maior de idade', 'Faz hora extra',
       'percentual de aumento de salário', 'score de performance',
       'Satisfação nas relações Não trabalho', 'Jornada padrão de trabalho',
       'opção de remaunração variável em ações', 'Total de anos trabalhados',
       'Qtde de treinamentos realizados no último ano',
       'Equilíbrio vida trabalho', 'Total de anos trabalhados na empresa',
       'Anos trabalhados na função atual', 'Anos desde a última promoção',
       'Anos trabalhando com o atual gestor'],
      dtype='object')

In [ ]:
df.shape # rows,cols

(1470, 35)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Idade                                           1470 non-null   int64
 1   Demissão                                        1470 non-null   object
 2   Viagem de negócios                              1470 non-null   object
 3   Diárias recebidas                               1470 non-null   int64
 4   Departamento                                    1470 non-null   object
 5   Distância de Casa                               1470 non-null   int64
 6   Escolaridade                                    1470 non-null   int64
 7   Área de Formação                                1470 non-null   object
 8   Número de contratos de trabalho na empresa      1470 non-null   int64
 9   ID Funcionário                                  1470 non-null   int64
 10  Nível de Satisfação com o ambiente de trabalho  1470 non-null   int64
 11  Gênero                                          1470 non-null   object
 12  Salário por hora                                1470 non-null   int64
 13  Nível de envolvimento com o trabalho            1470 non-null   int64
 14  Nível hierárquico                               1470 non-null   int64
 15  Cargo                                           1470 non-null   object
 16  Satisfação com o trabalho                       1470 non-null   int64
 17  Estado civil                                    1470 non-null   object
 18  Renda mensal                                    1470 non-null   int64
 19  Salário Mensal                                  1470 non-null   int64
 20  qtde de empresas que já trabalhou               1470 non-null   int64
 21  Maior de idade                                  1470 non-null   object
 22  Faz hora extra                                  1470 non-null   object
 23  percentual de aumento de salário                1470 non-null   int64
 24  score de performance                            1470 non-null   int64
 25  Satisfação nas relações Não trabalho            1470 non-null   int64
 26  Jornada padrão de trabalho                      1470 non-null   int64
 27  opção de remaunração variável em ações          1470 non-null   int64
 28  Total de anos trabalhados                       1470 non-null   int64
 29  Qtde de treinamentos realizados no último ano   1470 non-null   int64
 30  Equilíbrio vida trabalho                        1470 non-null   int64
 31  Total de anos trabalhados na empresa            1470 non-null   int64
 32  Anos trabalhados na função atual                1470 non-null   int64
 33  Anos desde a última promoção                    1470 non-null   int64
 34  Anos trabalhando com o atual gestor             1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

Retornou que não há objetos nulos e quantidade de conjuntos de dados:object, int64 e uso de memoria. Pandas utiliza series heterogeneas pode haver diversos tipos de dados dentro do tipo object.

## Exploração dos dados

**pd.value_counts()**: Conta as frequencias dos dados

**outliers**: os valores que são considerados alto e baixo dos restantes dos dados.

- Vamos falar que 75% is Q3 e value do Q1 é 25%;
- Outliers são menores que  Q1 - 1.5(Q3-Q1) e maiores que Q3 + 1.5(Q3-Q1).(Q3-Q1) = IQR. Vamos utilizar o **describe()** metodo.

- **describe()** inclui os metodos seguintes:
  - **count**: Numeros de entradas
  - **mean**: Média das entradas
  - **std**: Desvio padrão
  - **min**: Menor valor da entrada
  - **25%**: Primeiro quartil
  - **50%**: Mediana e segundo quartil
  - **75%**: Terceiro quartil
  - **max**: Maior entrada

# Normalização das columas para conseguir trabalhar melhor

In [ ]:
def clean_column_names(df):
    df.columns = df.columns.str.lower().str.strip().str.replace(' ', '_')

    for col in df.columns:
        df.rename(columns={col:unidecode(col)}, inplace=True)

    return df

clean_column_names(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   idade                                           1470 non-null   int64
 1   demissao                                        1470 non-null   object
 2   viagem_de_negocios                              1470 non-null   object
 3   diarias_recebidas                               1470 non-null   int64
 4   departamento                                    1470 non-null   object
 5   distancia_de_casa                               1470 non-null   int64
 6   escolaridade                                    1470 non-null   int64
 7   area_de_formacao                                1470 non-null   object
 8   numero_de_contratos_de_trabalho_na_empresa      1470 non-null   int64
 9   id_funcionario                                  1470 non-null   int64
 10  nivel_de_satisfacao_com_o_ambiente_de_trabalho  1470 non-null   int64
 11  genero                                          1470 non-null   object
 12  salario_por_hora                                1470 non-null   int64
 13  nivel_de_envolvimento_com_o_trabalho            1470 non-null   int64
 14  nivel_hierarquico                               1470 non-null   int64
 15  cargo                                           1470 non-null   object
 16  satisfacao_com_o_trabalho                       1470 non-null   int64
 17  estado_civil                                    1470 non-null   object
 18  renda_mensal                                    1470 non-null   int64
 19  salario_mensal                                  1470 non-null   int64
 20  qtde_de_empresas_que_ja_trabalhou               1470 non-null   int64
 21  maior_de_idade                                  1470 non-null   object
 22  faz_hora_extra                                  1470 non-null   object
 23  percentual_de_aumento_de_salario                1470 non-null   int64
 24  score_de_performance                            1470 non-null   int64
 25  satisfacao_nas_relacoes_nao_trabalho            1470 non-null   int64
 26  jornada_padrao_de_trabalho                      1470 non-null   int64
 27  opcao_de_remaunracao_variavel_em_acoes          1470 non-null   int64
 28  total_de_anos_trabalhados                       1470 non-null   int64
 29  qtde_de_treinamentos_realizados_no_ultimo_ano   1470 non-null   int64
 30  equilibrio_vida_trabalho                        1470 non-null   int64
 31  total_de_anos_trabalhados_na_empresa            1470 non-null   int64
 32  anos_trabalhados_na_funcao_atual                1470 non-null   int64
 33  anos_desde_a_ultima_promocao                    1470 non-null   int64
 34  anos_trabalhando_com_o_atual_gestor             1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [ ]:
df['total_de_anos_trabalhados_na_empresa'].describe()

count    1470.000000
mean        7.008163
std         6.126525
min         0.000000
25%         3.000000
50%         5.000000
75%         9.000000
max        40.000000
Name: total_de_anos_trabalhados_na_empresa, dtype: float64

In [ ]:
# # Verificar as 5 frequencias de anos de trabalhos dos 5 funcionarios mais antigo
# para o mais novo estes usuarios necessarimente precisa está ativo.


df_tmp = df['total_de_anos_trabalhados_na_empresa'].value_counts(
    dropna=False
).sort_index(
    ascending=False)

df_tmp.to_csv('Quantidade_funcionairos_mais_antigo.csv')
df_tmp.head(5)

total_de_anos_trabalhados_na_empresa
40    1
37    1
36    2
34    1
33    5
Name: count, dtype: int64

# TIDY DATA

In [ ]:
df_new = df.head(5)
df_new

,idade,demissao,viagem_de_negocios,diarias_recebidas,departamento,distancia_de_casa,escolaridade,area_de_formacao,numero_de_contratos_de_trabalho_na_empresa,id_funcionario,nivel_de_satisfacao_com_o_ambiente_de_trabalho,genero,salario_por_hora,nivel_de_envolvimento_com_o_trabalho,nivel_hierarquico,cargo,satisfacao_com_o_trabalho,estado_civil,renda_mensal,salario_mensal,qtde_de_empresas_que_ja_trabalhou,maior_de_idade,faz_hora_extra,percentual_de_aumento_de_salario,score_de_performance,satisfacao_nas_relacoes_nao_trabalho,jornada_padrao_de_trabalho,opcao_de_remaunracao_variavel_em_acoes,total_de_anos_trabalhados,qtde_de_treinamentos_realizados_no_ultimo_ano,equilibrio_vida_trabalho,total_de_anos_trabalhados_na_empresa,anos_trabalhados_na_funcao_atual,anos_desde_a_ultima_promocao,anos_trabalhando_com_o_atual_gestor
0,41,Sim,Viaja raramente,1102,Vendas,1,2,Ciências Humanas,1,1,2,Feminino,94,3,2,Executivo de vendas,4,Solteiro,5993,19479,8,Sim,Sim,11,3,1,80,0,8,0,1,6,4,0,5
1,49,Não,Viaja frequentemente,279,Pesquisa e Desenvolvimento,8,1,Ciências Humanas,1,2,3,Masculino,61,2,2,Pesquisador cientista,2,Casado,5130,24907,1,Sim,Não,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Sim,Viaja raramente,1373,Pesquisa e Desenvolvimento,2,2,Outras,1,4,4,Masculino,92,2,1,Técnico de Laboratório,3,Solteiro,2090,2396,6,Sim,Sim,15,3,2,80,0,7,3,3,0,0,0,0
3,33,Não,Viaja frequentemente,1392,Pesquisa e Desenvolvimento,3,4,Ciências Humanas,1,5,4,Feminino,56,3,1,Pesquisador cientista,3,Casado,2909,23159,1,Sim,Sim,11,3,3,80,0,8,3,3,8,7,3,0
4,27,Não,Viaja raramente,591,Pesquisa e Desenvolvimento,2,1,Ciências Médicas,1,7,1,Masculino,40,3,1,Técnico de Laboratório,2,Casado,3468,16632,9,Sim,Não,12,3,4,80,1,6,3,3,2,2,2,2

In [ ]:
## MELTED
df_melted = pd.melt(frame=df_new, id_vars='id_funcionario', value_vars=['demissao','total_de_anos_trabalhados_na_empresa'])
df_melted.head(10)

   id_funcionario                              variable value
0               1                              demissao   Sim
1               2                              demissao   Não
2               4                              demissao   Sim
3               5                              demissao   Não
4               7                              demissao   Não
5               1  total_de_anos_trabalhados_na_empresa     6
6               2  total_de_anos_trabalhados_na_empresa    10
7               4  total_de_anos_trabalhados_na_empresa     0
8               5  total_de_anos_trabalhados_na_empresa     8
9               7  total_de_anos_trabalhados_na_empresa     2

### PIVTOTING DATA

In [ ]:
# Verificando quais id_funcionarios  estão na ativa que são mais antigos
df_pivot = df_melted.pivot(index='id_funcionario',
                           columns='variable',
                           values='value')



result = df_pivot.loc[df_pivot['demissao'] == 'Não'].sort_values(
    by='total_de_anos_trabalhados_na_empresa',
    ascending=False
)

result

variable       demissao total_de_anos_trabalhados_na_empresa
id_funcionario
2                   Não                                   10
5                   Não                                    8
7                   Não                                    2

In [ ]:
# Quantidades de funcionarios agrupoados por ativos e não ativos

df_pivot['demissao'].value_counts(dropna=False)

demissao
Não    3
Sim    2
Name: count, dtype: int64

# Atividade

[link text](https://)# 1. Taxa de Rotavidade

### 1. Taxa de Rotavidade

In [ ]:
# Taxa de Rotatividade ->
#taxa_rotatividade = (numeros_uncionarios_nao_ativos)/ numeros_funcionarios) * 100

df_inactive_employees = df['demissao'].value_counts()
display(df_inactive_employees)
rate_turnover  = df_inactive_employees['Sim'] / len(df) * 100


df_inactive_employees.to_csv('inactive_employees.csv')
print('-'*80)
print(f'Taxa de rotatividade: {rate_turnover:.2f}')

demissao
Não    1233
Sim     237
Name: count, dtype: int64

--------------------------------------------------------------------------------
Taxa de rotatividade: 16.12

### 2. Rotavidade por experiencia de funcionario

In [ ]:
df_transform = df[['demissao','total_de_anos_trabalhados_na_empresa']]

# display(df_transform['total_de_anos_trabalhados_na_empresa'].describe())
bins = [0, 3, 5, 9, 40]
labels = ["Novatos", "Iniciante", "Experiente", "Senior"]

df_transform['categoria'] = pd.cut(df_transform['total_de_anos_trabalhados_na_empresa'], bins=bins, labels=labels, right=False)
df_transform_filtered_inactive_employess = df_transform[df['demissao'] == 'Sim']
total_inactive_employess = len(df_transform_filtered_inactive_employess)

print(f'Total de funcionarios desligados: {total_inactive_employess}')

# display(df_transform_filtered_inactive_employess.value_counts('categoria'))

total_employess_by_category = df_transform_filtered_inactive_employess['categoria']
total_employess_by_category = total_employess_by_category.value_counts()
df_result = total_employess_by_category.rename('total funcionarios desligados por experiencia')

df_result.to_csv('df_rotatividade_por_experiencia.csv')
df_result

Total de funcionarios desligados: 237

<ipython-input-18-660ed466bfd1>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_transform['categoria'] = pd.cut(df_transform['total_de_anos_trabalhados_na_empresa'], bins=bins, labels=labels, right=False)

categoria
Novatos       102
Experiente     50
Senior         45
Iniciante      39
Name: total funcionarios desligados por experiencia, dtype: int64

### 3. Quantidade de Rotatividade por genero

In [ ]:
df_turnover_gender = df.loc[:,('genero','demissao')]
df_filtered_gender_count = df_turnover_gender.loc[:, 'genero'].value_counts()
# display(df_filtered_gender_count)


df_result = pd.crosstab(df_turnover_gender['genero'],df_turnover_gender['demissao'])
df_result.to_csv('df_quantidade_rotatividade_por_genero.csv')
display(df_result)

demissao   Não  Sim
genero
Feminino   501   87
Masculino  732  150

### 4. Nivel de maturidade dos coloaboradores da empresa

In [ ]:
'''
Nivel de maturidade dos coloaboradores da empresa
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


'''
df_transform = df.loc[:,('total_de_anos_trabalhados_na_empresa','demissao')]
bins = [0, 3, 5, 9, 40]
labels = ["Novatos", "Iniciante", "Experiente", "Senior"]

df_transform['categoria'] = pd.cut(df_transform['total_de_anos_trabalhados_na_empresa'],
                                   bins=bins,
                                   labels=labels,
                                   right=False)

df_transform_filtered_active_employess = df_transform[df['demissao'] == 'Não']
total_active_employess = len(df_transform_filtered_active_employess)

# To normalize value counts in a pandas Series, use the normalize argument.
df_percentage_active_employess = df_transform_filtered_active_employess['categoria'].value_counts(
    normalize=True).mul(100).round(2).rename('%')

print(f'Total de funcionarios ativos: {total_active_employess}')
df_result = pd.concat([df_transform_filtered_active_employess.value_counts('categoria'),
                       df_percentage_active_employess],axis=1)

df_result.to_csv('df_nivel_maturidades dos colabores da empresa.csv')
df_result

Total de funcionarios ativos: 1233

            count      %
categoria
Senior        402  32.60
Experiente    392  31.79
Novatos       240  19.46
Iniciante     199  16.14

### 5. Perfil Demográfico dos Funcionários: Distribuição Etária [Adulto, Adulto Senior, Senior]|

In [ ]:
df_demographic_age = df.loc[:,('genero', 'idade')]

df_demographic_age['idade'].describe()

labels = ['Adulto', 'Adulto Senior', 'Senior']
bins = [18, 54, 64, 100]

df_demographic_age['faixa_etaria'] = pd.cut(df_demographic_age['idade'],
                                            bins=bins,
                                            labels=labels,
                                            right=False)

df_result = df_demographic_age['faixa_etaria'].value_counts(normalize=True).rename('%').mul(100).round(2)
df_result.to_csv('df_perfil_demografico_dos_funcionarios.csv')
df_result

faixa_etaria
Adulto           94.08
Adulto Senior     5.92
Senior            0.00
Name: %, dtype: float64

## 6. Perfil demográfico dos funcionarios: Genero
\

In [ ]:
df_demographic_age  = df.loc[:,('genero', 'idade')]
df_result = df_demographic_age['genero'].value_counts(normalize=True).rename('%').mul(100).round(2)
df_result.to_csv('df_perfil_demografico_dos_funcionarios_genero.csv')
df_result

genero
Masculino    60.0
Feminino     40.0
Name: %, dtype: float64

## 7. Perfil demográfico dos funcionarios: Genero X Cargo

In [ ]:
df_demographic_age_position = df.loc[df['demissao'] == 'Não',('genero', 'cargo', 'idade')]

df_demographic_age_position = df_demographic_age_position.groupby(['genero', 'cargo']).size().rename('quantidade').reset_index()
df_demographic_age_position.to_csv('df_perfil_demografico_dos_funcionarios_genero_cargo.csv')
df_demographic_age_position.groupby(['genero'])

## 8. Perfil demográfico dos funcionarios: Verificar os generos e cargos com os salarios mais alto funcionarios

In [ ]:
df_demographic_gender_salary = df.loc[df['demissao'] == 'Não',('genero', 'salario_mensal','cargo','area_de_formacao')]
df_demographic_gender_salary.groupby(['genero', 'salario_mensal'])

df_result = df_demographic_gender_salary.sort_values(by='salario_mensal',ascending=False).head(5)
df_result.to_csv('df_perfil_demografico_dos_funcionarios_genero_salario.csv')
df_result

         genero  salario_mensal                   cargo  area_de_formacao
1350   Feminino           26997     Executivo de vendas  Ciências Médicas
808    Feminino           26968   Pesquisador cientista  Ciências Humanas
859    Feminino           26933   Pesquisador cientista  Ciências Humanas
386    Feminino           26914  Técnico de Laboratório  Ciências Humanas
108   Masculino           26897   Pesquisador cientista  Ciências Médicas

## **9**. Quantidade de funcionarios na ativa X formação

In [ ]:
df_graduate_training = df.loc[df['demissao'] == 'Não',('id_funcionario','area_de_formacao','escolaridade','genero')]

df_result = df_graduate_training.groupby('area_de_formacao').size().rename('quantidade')
df_result.to_csv('df_quantidade_funcionarios_formacao.csv')
df_result

area_de_formacao
Ciências Humanas     517
Ciências Médicas     401
EnsiNão técnico      100
Marketing            124
Outras                71
Recursos HumaNãos     20
Name: quantidade, dtype: int64

## 10. Média de desempenho da equipe

In [ ]:
df_demographic_gender_performance = df.loc[df['demissao'] == "Não",('score_de_performance','genero')]
mean_team = df_demographic_gender_performance['score_de_performance'].mean()
data = {'media_equipe': mean_team}
df_result = pd.DataFrame(data,index=[0])
df_result.to_csv('df_media_desempenho_equipe.csv')
df_result

   media_equipe
0      3.153285

## 11. Media de desempenho por genero

In [ ]:
df_result = df_demographic_gender_performance.groupby('genero').mean()
display(df_result)


data_gender = {'media_feminina': df_result.iloc[0,0],
               'media_masculina': df_result.iloc[1,0]}
data_result = data | data_gender

df_result = pd.DataFrame(data_result,index=['score_perfomance'])
df_result.to_csv('df_media_desempenho_por_genero.csv')
df_result

           score_de_performance
genero
Feminino               3.157685
Masculino              3.150273

                  media_equipe  media_feminina  media_masculina
score_perfomance      3.153285        3.157685         3.150273

## 12. Analisar de Desempenho dos usuarios ativos

In [ ]:
df_evaluate_performance_active = df.loc[df['demissao'] == "Não",('id_funcionario','score_de_performance','genero','cargo')]

# df_evaluate_performance_active['score_de_performance'].describe()
df_result = df_evaluate_performance_active['score_de_performance'].value_counts().rename('quantidade')
df_result.to_csv('df_desempenho_usuarios_ativos.csv')
df_result

score_de_performance
3    1044
4     189
Name: quantidade, dtype: int64

## 13. Contar o número de funcionários que deixaram a empresa em cada grupo

In [ ]:
df_evaluate_performance_inactive = df.loc[df['demissao'] == "Sim",('id_funcionario','score_de_performance','genero','cargo')]
df_result = df_evaluate_performance_inactive['score_de_performance'].value_counts().rename('quantidade')
df_result.to_csv('df_desempenho_usuarios_desligados.csv')
df_result

score_de_performance
3    200
4     37
Name: quantidade, dtype: int64

## 14. Taxa de Rotatividade por Desempenho

In [ ]:
total_inactive_employess = len(df_evaluate_performance_inactive)
number_evaluate_perfomance_inactive = df_evaluate_performance_inactive['score_de_performance'].value_counts().rename('quantidade')
# total_inactive_employess_1.info()

df_number_evaluate_perfomance_inactive = number_evaluate_perfomance_inactive.to_frame()
df_number_evaluate_perfomance_inactive['percentual'] = (df_number_evaluate_perfomance_inactive['quantidade']
                                            / total_inactive_employess * 100).round(2)
df_number_evaluate_perfomance_inactive.to_csv('df_taxa_rotatividade_por_desempenho.csv')
df_number_evaluate_perfomance_inactive



# total_score_perfomance_3 = total_inactive_employess_1[3]
# total_score_perfomance_3

                      quantidade  percentual
score_de_performance
3                            200       84.39
4                             37       15.61

## 15. Quantidade de funcionario categoria por Distância até o Trabalho

In [ ]:
df_distance_work = df.loc[df['demissao'] == 'Não' ,('id_funcionario','distancia_de_casa')]
# df_distance_work['distancia_de_casa'].describe()

bins = [ 0, 14, 21, float('inf')] # float('inf') infinito positivo
labels = ['proximo', 'medio', 'distante']

df_distance_work['categoria'] = pd.cut(df_distance_work['distancia_de_casa'],
                                       bins=bins,
                                       labels=labels)
df_result = (df_distance_work['categoria'].value_counts().rename('quantidade'))
df_result.to_csv('df_quantidade_funcionario_categoria_distancia_trabalho.csv')
display(df_result)

categoria
proximo     951
distante    144
medio       138
Name: quantidade, dtype: int64

In [ ]:
df_result.keys()

CategoricalIndex(['proximo', 'distante', 'medio'], categories=['proximo', 'medio', 'distante'], ordered=True, dtype='category', name='categoria')

## 16. Rotatividade X Distância até o Trabalho

In [ ]:
df_distance_work_2 = df.loc[df['demissao'] == 'Sim',('id_funcionario','distancia_de_casa','demissao')]
total_inactive_employess = len(df_distance_work_2)

bins = [ 0, 14, 21, float('inf')] # float('inf') infinito positivo
labels = ['proximo', 'medio', 'distante']

df_distance_work_2['categoria'] = pd.cut(df_distance_work_2['distancia_de_casa'],
                                       bins=bins,
                                       labels=labels)

df_distance_work_2 = df_distance_work_2.groupby('categoria').size().rename('quantidade')
df_distance_work_2 = df_distance_work_2.to_frame()
df_distance_work_2['percentual'] = (df_distance_work_2['quantidade']
                                            / total_inactive_employess * 100).round(2)

df_distance_work_2.to_csv('df_rotatividade_x_distancia_trabalho.csv')
df_distance_work_2

<ipython-input-33-a462818b5a90>:11: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_distance_work_2 = df_distance_work_2.groupby('categoria').size().rename('quantidade')

           quantidade  percentual
categoria
proximo           164       69.20
medio              31       13.08
distante           42       17.72

## 17. Para cada departamento, conte o número total de funcionários.

In [ ]:
df_department = df.loc[:,('id_funcionario','departamento','demissao')]

df_result = df_department.groupby(['departamento', 'demissao']).size().rename('quantidade')
df_result.to_csv('df_total_funcionarios_departamento.csv')
df_result

departamento                demissao
Pesquisa e Desenvolvimento  Não         828
                            Sim         133
Recursos HumaNãos           Não          51
                            Sim          12
Vendas                      Não         354
                            Sim          92
Name: quantidade, dtype: int64

## 18. Calcule a taxa de rotatividade para cada departamento usando

In [ ]:
df_department_2 = df.loc[df['demissao'] == 'Sim',('id_funcionario','departamento','demissao')]
total_inactive_employess = len(df_department_2)

df_result = df_department_2.groupby(['departamento']).size().rename('quantidade')
df_result = df_result.to_frame()
df_result['percentual'] = (df_result['quantidade']
                                            / total_inactive_employess * 100).round(2)
df_result.to_csv('df_total_funcionarios_departamento.csv')
df_result

                            quantidade  percentual
departamento
Pesquisa e Desenvolvimento         133       56.12
Recursos HumaNãos                   12        5.06
Vendas                              92       38.82

## 19 . Analise dos Funcionários ativos que receberam **promoção**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   idade                                           1470 non-null   int64
 1   demissao                                        1470 non-null   object
 2   viagem_de_negocios                              1470 non-null   object
 3   diarias_recebidas                               1470 non-null   int64
 4   departamento                                    1470 non-null   object
 5   distancia_de_casa                               1470 non-null   int64
 6   escolaridade                                    1470 non-null   int64
 7   area_de_formacao                                1470 non-null   object
 8   numero_de_contratos_de_trabalho_na_empresa      1470 non-null   int64
 9   id_funcionario                                  1470 non-null   int64
 10  nivel_de_satisfacao_com_o_ambiente_de_trabalho  1470 non-null   int64
 11  genero                                          1470 non-null   object
 12  salario_por_hora                                1470 non-null   int64
 13  nivel_de_envolvimento_com_o_trabalho            1470 non-null   int64
 14  nivel_hierarquico                               1470 non-null   int64
 15  cargo                                           1470 non-null   object
 16  satisfacao_com_o_trabalho                       1470 non-null   int64
 17  estado_civil                                    1470 non-null   object
 18  renda_mensal                                    1470 non-null   int64
 19  salario_mensal                                  1470 non-null   int64
 20  qtde_de_empresas_que_ja_trabalhou               1470 non-null   int64
 21  maior_de_idade                                  1470 non-null   object
 22  faz_hora_extra                                  1470 non-null   object
 23  percentual_de_aumento_de_salario                1470 non-null   int64
 24  score_de_performance                            1470 non-null   int64
 25  satisfacao_nas_relacoes_nao_trabalho            1470 non-null   int64
 26  jornada_padrao_de_trabalho                      1470 non-null   int64
 27  opcao_de_remaunracao_variavel_em_acoes          1470 non-null   int64
 28  total_de_anos_trabalhados                       1470 non-null   int64
 29  qtde_de_treinamentos_realizados_no_ultimo_ano   1470 non-null   int64
 30  equilibrio_vida_trabalho                        1470 non-null   int64
 31  total_de_anos_trabalhados_na_empresa            1470 non-null   int64
 32  anos_trabalhados_na_funcao_atual                1470 non-null   int64
 33  anos_desde_a_ultima_promocao                    1470 non-null   int64
 34  anos_trabalhando_com_o_atual_gestor             1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [ ]:
df_employees_promotion = df.loc[df['demissao'] == "Não",('id_funcionario','anos_desde_a_ultima_promocao')]
df_employees_promotion['anos_desde_a_ultima_promocao'].describe()

labels = ['recente', 'antigo']
bins = [0, 3, float('inf')]

df_employees_promotion['categoria'] = pd.cut(df_employees_promotion['anos_desde_a_ultima_promocao'],
                                       bins=bins,
                                       labels=labels)
df_result = (df_employees_promotion['categoria'].value_counts().rename('quantidade'))
df_result.to_csv('df_relacao_promocoes_desgaste_funcionarios.csv')
df_result

categoria
recente    483
antigo     279
Name: quantidade, dtype: int64

## 20 . Analise dos Funcionários que receberam **promoção** relacionado a desgaste.

In [ ]:
df_employees_promotion = df.loc[:,('id_funcionario','anos_desde_a_ultima_promocao','demissao')]
df_employees_promotion['anos_desde_a_ultima_promocao'].describe()

labels = ['recente', 'antigo']
bins = [0, 3, float('inf')]

employees_promotion_category = pd.cut(df_employees_promotion['anos_desde_a_ultima_promocao'],
                                       bins=bins,
                                       labels=labels,right=False)



df_result = employees_promotion_category.to_frame()
df_result['demissao'] = df_employees_promotion['demissao']
df_result = df_result.groupby(['anos_desde_a_ultima_promocao','demissao']).size().rename('quantidade')
df_result.to_csv('df_relacao_promocoes_desgaste_funcionarios.csv')
df_result

<ipython-input-111-d16d78555fab>:15: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_result = df_result.groupby(['anos_desde_a_ultima_promocao','demissao']).size().rename('quantidade')

anos_desde_a_ultima_promocao  demissao
recente                       Não         911
                              Sim         186
antigo                        Não         322
                              Sim          51
Name: quantidade, dtype: int64

## Referencias

- https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
- https://escoladedados.org/tutoriais/tidy-data-dados-arrumados-e-5-problemas-comuns/